# Generated by Django 5.2.17 on 2026-09-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_version",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="Incremented to invalidate every existing login session of this user.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUPER_ADMIN", "Super admin"),
                    ("ADMIN", "Admin"),
                    ("FINANCE_ADMIN", "Finance admin"),
                    ("COACH", "Coach"),
                    ("PARENT", "Parent"),
                    ("STUDENT", "Student"),
                ],
                default="",
                editable=False,
                help_text="Display only: the highest-ranking role. Authorization uses the user's groups.",
                max_length=20,
            ),
        ),
    ]
