# Generated by Django 5.2.17 on 2026-09-30 04:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_role_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        help_text="As typed, lower-cased.",
                        max_length=150,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                (
                    "locked",
                    models.BooleanField(
                        default=False,
                        help_text="The attempt was refused because of the lockout.",
                    ),
                ),
                (
                    "attempted_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "ordering": ["-attempted_at"],
            },
        ),
    ]
