# Generated by Django 5.2.17 on 2026-09-29 07:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academy", "0002_initial"),
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("organiser", models.CharField(blank=True, max_length=200)),
                ("venue", models.CharField(blank=True, max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("registration_deadline", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft (hidden from parents)"),
                            ("OPEN", "Open for registration"),
                            ("CLOSED", "Registration closed"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("allow_parent_registration", models.BooleanField(default=True)),
                (
                    "max_events_per_student",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "age_reference_date",
                    models.DateField(
                        blank=True,
                        help_text="Date used to calculate age for age groups (defaults to the start date).",
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="CompetitionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CHANGQUAN", "Changquan"),
                            ("NANQUAN", "Nanquan"),
                            ("TAIJIQUAN", "Taijiquan"),
                            ("JIANSHU", "Jianshu"),
                            ("DAOSHU", "Daoshu"),
                            ("GUNSHU", "Gunshu"),
                            ("QIANGSHU", "Qiangshu"),
                            ("NANDAO", "Nandao"),
                            ("NANGUN", "Nangun"),
                            ("TAIJIJIAN", "Taijijian"),
                            ("SANDA", "Sanda"),
                            ("DUILIAN", "Duilian"),
                            ("GROUP", "Group set"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='e.g. "Changquan – Boys U12"', max_length=150
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("OPEN", "Open / mixed"),
                        ],
                        default="OPEN",
                        max_length=4,
                    ),
                ),
                ("min_age", models.PositiveIntegerField(blank=True, null=True)),
                ("max_age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "weight_class",
                    models.CharField(blank=True, help_text="For Sanda.", max_length=50),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("max_entries", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="competitions.competition",
                    ),
                ),
            ],
            options={
                "ordering": ["competition", "event_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="CompetitionRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending coach/admin approval"),
                            ("CONFIRMED", "Confirmed"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "charge",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competition_registration",
                        to="finance.charge",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="competitions.competitionevent",
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competition_registrations",
                        to="academy.student",
                    ),
                ),
            ],
            options={
                "ordering": ["event", "student__full_name"],
            },
        ),
        migrations.CreateModel(
            name="CompetitionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placing", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "medal",
                    models.CharField(
                        choices=[
                            ("GOLD", "Gold"),
                            ("SILVER", "Silver"),
                            ("BRONZE", "Bronze"),
                            ("NONE", "No medal"),
                        ],
                        default="NONE",
                        max_length=6,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=255)),
                ("recorded_at", models.DateTimeField(auto_now=True)),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="result",
                        to="competitions.competitionregistration",
                    ),
                ),
            ],
            options={
                "ordering": ["registration__event", "placing"],
            },
        ),
        migrations.AddConstraint(
            model_name="competitionevent",
            constraint=models.UniqueConstraint(
                fields=("competition", "name"), name="unique_event_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="competitionregistration",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["WITHDRAWN", "REJECTED"]), _negated=True
                ),
                fields=("event", "student"),
                name="one_active_registration_per_event",
            ),
        ),
    ]
