# Generated by Django 5.2.17 on 2026-09-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitionregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Awaiting payment"),
                    ("CONFIRMED", "Confirmed"),
                    ("WITHDRAWN", "Withdrawn"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
