# Generated by Django 5.2.17 on 2026-09-30 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0003_result_requires_confirmed_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="allow_parent_withdrawal",
            field=models.BooleanField(
                default=True,
                help_text="Parents may withdraw their own entries while registration is open. Refunds are never automatic; exceptional refunds are a finance action.",
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="form_published_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="competition",
            name="form_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft (parents cannot register)"),
                    ("PUBLISHED", "Published"),
                ],
                default="PUBLISHED",
                editable=False,
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="form_version",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="competition",
            name="published_form",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name="competition",
            name="rules",
            field=models.TextField(
                blank=True,
                help_text="Competition rules shown to parents (e.g. categories, equipment).",
            ),
        ),
        migrations.AddField(
            model_name="competitionregistration",
            name="form_responses",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name="competitionregistration",
            name="form_version",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name="RegistrationFormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Stable identifier, e.g. shirt_size (lowercase, digits, _).",
                        max_length=40,
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Short text"),
                            ("LONG_TEXT", "Long text"),
                            ("NUMBER", "Number"),
                            ("DATE", "Date"),
                            ("SINGLE_SELECT", "Single choice"),
                            ("MULTI_SELECT", "Multiple choice"),
                            ("YES_NO", "Yes / No"),
                            ("EMAIL", "Email"),
                            ("PHONE", "Phone"),
                        ],
                        max_length=15,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("help_text", models.CharField(blank=True, max_length=255)),
                ("placeholder", models.CharField(blank=True, max_length=100)),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Choices for single / multiple choice fields.",
                    ),
                ),
                (
                    "max_length",
                    models.PositiveIntegerField(
                        blank=True, help_text="Text fields only.", null=True
                    ),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_fields",
                        to="competitions.competition",
                    ),
                ),
            ],
            options={
                "ordering": ["competition", "order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("competition", "key"), name="unique_form_field_key"
                    )
                ],
            },
        ),
    ]
