# Generated by Django 5.2.17 on 2026-09-29 07:44

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academy", "0001_initial"),
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChargeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("TUITION", "Tuition / class fee"),
                            ("REGISTRATION", "Registration fee"),
                            ("UNIFORM", "Uniform fee"),
                            ("WEAPON", "Weapon charges"),
                            ("COMPETITION", "Competition fee"),
                            ("OTHER", "Other charges"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "default_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["fee_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="ReceiptSequence",
            fields=[
                (
                    "year",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ClassFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='e.g. "Monthly fee", "Monthly fee (3x/week)"',
                        max_length=100,
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("TUITION", "Tuition / class fee"),
                            ("REGISTRATION", "Registration fee"),
                            ("UNIFORM", "Uniform fee"),
                            ("WEAPON", "Weapon charges"),
                            ("COMPETITION", "Competition fee"),
                            ("OTHER", "Other charges"),
                        ],
                        default="TUITION",
                        max_length=12,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Per month"),
                            ("PER_SESSION", "Per session attended"),
                            ("TERM", "Per term"),
                            ("YEARLY", "Per year"),
                            ("ONE_TIME", "One time"),
                        ],
                        default="MONTHLY",
                        max_length=12,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=True,
                        help_text="Used for students in this class who have no specific fee plan.",
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "training_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fees",
                        to="academy.trainingclass",
                    ),
                ),
            ],
            options={
                "ordering": ["training_class", "name", "-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="Charge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("TUITION", "Tuition / class fee"),
                            ("REGISTRATION", "Registration fee"),
                            ("UNIFORM", "Uniform fee"),
                            ("WEAPON", "Weapon charges"),
                            ("COMPETITION", "Competition fee"),
                            ("OTHER", "Other charges"),
                        ],
                        max_length=12,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1"), max_digits=8
                    ),
                ),
                (
                    "unit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="quantity × unit amount − discount",
                        max_digits=10,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Unpaid"),
                            ("PARTIAL", "Partially paid"),
                            ("PAID", "Paid"),
                            ("WAIVED", "Waived"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="UNPAID",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="academy.enrollment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="academy.student",
                    ),
                ),
                (
                    "charge_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="finance.chargeitem",
                    ),
                ),
                (
                    "class_fee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="finance.classfee",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payer_name", models.CharField(max_length=200)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK_TRANSFER", "Bank transfer"),
                            ("DUITNOW", "DuitNow / QR"),
                            ("FPX", "FPX online banking"),
                            ("CARD", "Debit / credit card"),
                            ("CHEQUE", "Cheque"),
                            ("EWALLET", "E-wallet (TNG, GrabPay, ...)"),
                            ("OTHER", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Bank / transaction reference, cheque no.",
                        max_length=100,
                    ),
                ),
                ("received_on", models.DateField(default=datetime.date.today)),
                (
                    "status",
                    models.CharField(
                        choices=[("VALID", "Valid"), ("VOIDED", "Voided")],
                        default="VALID",
                        max_length=6,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="accounts.parent",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-received_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PaymentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "charge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="finance.charge",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="finance.payment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30, unique=True)),
                ("issued_at", models.DateTimeField()),
                ("payer_name", models.CharField(max_length=200)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "content",
                    models.JSONField(help_text="Frozen receipt content as issued."),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt",
                        to="finance.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ReceiptVoid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voided_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField()),
                (
                    "receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="void_record",
                        to="finance.receipt",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentFeePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Overrides the fee amount.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "class_fee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pick one of the class's fee options. Leave empty to use the class default.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.classfee",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fee_plans",
                        to="academy.enrollment",
                    ),
                ),
            ],
            options={
                "ordering": ["enrollment", "-start_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="charge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "CANCELLED"), _negated=True),
                fields=("enrollment", "class_fee", "period_start"),
                name="unique_active_period_charge",
            ),
        ),
    ]
