# Generated by Django 5.2.17 on 2026-09-30 08:16

import apps.finance.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0006_session_lifecycle"),
        ("finance", "0003_protect_financial_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademyPaymentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("account_name", models.CharField(blank=True, max_length=150)),
                ("account_number", models.CharField(blank=True, max_length=40)),
                (
                    "instructions",
                    models.TextField(
                        blank=True, help_text="How to pay (shown to parents)."
                    ),
                ),
                (
                    "reference_instructions",
                    models.CharField(
                        blank=True,
                        default="Use the invoice number as the payment reference.",
                        max_length=255,
                    ),
                ),
                (
                    "qr_code",
                    models.FileField(
                        blank=True,
                        help_text="PNG or JPEG payment QR (e.g. DuitNow).",
                        max_length=255,
                        storage=apps.finance.models._private_storage,
                        upload_to="",
                    ),
                ),
                (
                    "qr_content_type",
                    models.CharField(blank=True, editable=False, max_length=20),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "academy payment information",
                "verbose_name_plural": "academy payment information",
            },
        ),
        migrations.CreateModel(
            name="PaymentProof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        editable=False,
                        max_length=255,
                        storage=apps.finance.models._private_storage,
                        upload_to="",
                    ),
                ),
                ("original_name", models.CharField(editable=False, max_length=120)),
                ("content_type", models.CharField(editable=False, max_length=40)),
                ("size", models.PositiveIntegerField(editable=False)),
                ("sha256", models.CharField(editable=False, max_length=64)),
                (
                    "amount_claimed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pending review"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING_REVIEW",
                        editable=False,
                        max_length=15,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("review_note", models.TextField(blank=True, editable=False)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_proofs",
                        to="academy.family",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_proofs",
                        to="finance.invoice",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="The payment staff recorded for this proof, if linked.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_proofs",
                        to="finance.payment",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("reviewed_at__isnull", True),
                                ("status", "PENDING_REVIEW"),
                            ),
                            models.Q(
                                ("reviewed_at__isnull", False),
                                ("status__in", ["ACCEPTED", "REJECTED"]),
                            ),
                            _connector="OR",
                        ),
                        name="proof_review_matches_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "REJECTED"), _negated=True),
                            models.Q(("review_note", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="proof_rejection_has_reason",
                    ),
                ],
            },
        ),
    ]
