# Generated by Django 5.2.17 on 2026-09-29 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academy", "0001_initial"),
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="classcoach",
            name="coach",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="class_assignments",
                to="accounts.coach",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="coach",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional personal/primary coach for this student in this class.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="personal_students",
                to="accounts.coach",
            ),
        ),
        migrations.AddField(
            model_name="guardianship",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="guardianships",
                to="accounts.parent",
            ),
        ),
        migrations.AddField(
            model_name="sessioncoach",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sessioncoach",
            name="coach",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="session_slots",
                to="accounts.coach",
            ),
        ),
        migrations.AddField(
            model_name="sessioncoach",
            name="replaces",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replaced_in_slots",
                to="accounts.coach",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="parents",
            field=models.ManyToManyField(
                related_name="children",
                through="academy.Guardianship",
                to="accounts.parent",
            ),
        ),
        migrations.AddField(
            model_name="guardianship",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="guardianships",
                to="academy.student",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollments",
                to="academy.student",
            ),
        ),
        migrations.AddField(
            model_name="studentstatushistory",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="status_history",
                to="academy.student",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="academy.program",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollments",
                to="academy.team",
            ),
        ),
        migrations.AddField(
            model_name="trainingclass",
            name="coaches",
            field=models.ManyToManyField(
                related_name="classes",
                through="academy.ClassCoach",
                to="accounts.coach",
            ),
        ),
        migrations.AddField(
            model_name="trainingclass",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classes",
                to="academy.program",
            ),
        ),
        migrations.AddField(
            model_name="trainingclass",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classes",
                to="academy.team",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="training_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollments",
                to="academy.trainingclass",
            ),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="training_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="academy.trainingclass",
            ),
        ),
        migrations.AddField(
            model_name="classcoach",
            name="training_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="coach_assignments",
                to="academy.trainingclass",
            ),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="training_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="academy.trainingclass",
            ),
        ),
        migrations.AddField(
            model_name="sessioncoach",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coach_slots",
                to="academy.trainingsession",
            ),
        ),
        migrations.AddConstraint(
            model_name="guardianship",
            constraint=models.UniqueConstraint(
                fields=("student", "parent"), name="unique_guardianship"
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("end_date__isnull", True)),
                fields=("student", "training_class"),
                name="one_open_enrollment_per_class",
            ),
        ),
        migrations.AddConstraint(
            model_name="classcoach",
            constraint=models.UniqueConstraint(
                condition=models.Q(("end_date__isnull", True)),
                fields=("training_class", "coach"),
                name="one_open_assignment_per_coach_class",
            ),
        ),
        migrations.AddConstraint(
            model_name="trainingsession",
            constraint=models.UniqueConstraint(
                fields=("training_class", "date", "start_time"),
                name="unique_session_slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessioncoach",
            constraint=models.UniqueConstraint(
                fields=("session", "coach"), name="unique_coach_per_session"
            ),
        ),
    ]
