# Generated by Django 5.2.17 on 2026-09-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="category",
            field=models.CharField(
                choices=[
                    ("GENERAL", "General"),
                    ("STUDENT", "Student"),
                    ("CLASS", "Class"),
                    ("ATTENDANCE", "Attendance"),
                    ("FINANCE", "Finance"),
                    ("COMPETITION", "Competition"),
                    ("PAYROLL", "Payroll"),
                    ("ACCESS", "Access"),
                    ("SECURITY", "Security & roles"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
