# Generated by Django 5.2.17 on 2026-09-30 04:43

"""Audit log hardening (Phase 5).

* New columns: the client's IP address and user agent.
* One-time redaction of entries written before masking existed: IC / passport,
  bank account, EPF and SOCSO numbers keep only their last 4 characters,
  medical notes are replaced by "[MEDICAL NOTE – n characters]", and any
  credential-like field is replaced by "[SECRET]". This deliberately rewrites
  those values once (it cannot be undone): keeping raw identity numbers and
  medical notes in the audit trail was the privacy problem being fixed. Who
  changed what and when is kept.
* PostgreSQL trigger: audit entries can never be updated or deleted, except that
  the actor may become NULL when that user account is deleted.

The masking rules are copied here (not imported) so this migration keeps doing
exactly what it did when it was written.
"""

import re

from django.db import migrations, models

IDENTIFIER_FIELDS = {"ic_number", "nric", "passport_no", "passport_number", "bank_account_no", "epf_no", "socso_no"}
MEDICAL_FIELDS = {"medical_notes"}
SECRET_FIELD = re.compile(r"(?i)(^|_)(password|passwd|secret|token|api_?key|private_?key|auth_version|key)$")


def _mask(field, value):
    if value in (None, ""):
        return value
    text = str(value)
    if SECRET_FIELD.search(field):
        return "[SECRET]"
    if field in IDENTIFIER_FIELDS:
        if text.startswith("*"):
            return text  # already masked
        return "*" * len(text) if len(text) <= 4 else "*" * (len(text) - 4) + text[-4:]
    if field in MEDICAL_FIELDS:
        return text if text.startswith("[MEDICAL NOTE") else f"[MEDICAL NOTE – {len(text)} characters]"
    return value


def redact_existing(apps, schema_editor):
    AuditLog = apps.get_model("audit", "AuditLog")
    sensitive = IDENTIFIER_FIELDS | MEDICAL_FIELDS
    for entry in AuditLog.objects.all().only("id", "changes").iterator():
        changes = entry.changes or {}
        new = {}
        for field, change in changes.items():
            if field in sensitive or SECRET_FIELD.search(field):
                if isinstance(change, dict):
                    new[field] = {k: _mask(field, v) for k, v in change.items()}
                else:
                    new[field] = _mask(field, change)
            else:
                new[field] = change
        if new != changes:
            AuditLog.objects.filter(pk=entry.pk).update(changes=new)
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE", params=None)


FORWARD_SQL = """
CREATE OR REPLACE FUNCTION sr_guard_auditlog() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'SR Wushu audit log: entries cannot be deleted' USING ERRCODE = 'restrict_violation';
    END IF;
    IF (to_jsonb(OLD) - 'actor_id') IS DISTINCT FROM (to_jsonb(NEW) - 'actor_id')
       OR (NEW.actor_id IS NOT NULL AND NEW.actor_id IS DISTINCT FROM OLD.actor_id) THEN
        RAISE EXCEPTION 'SR Wushu audit log: entries cannot be modified' USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END; $$ LANGUAGE plpgsql;

CREATE TRIGGER sr_auditlog_guard BEFORE UPDATE OR DELETE ON audit_auditlog
    FOR EACH ROW EXECUTE FUNCTION sr_guard_auditlog();
"""

BACKWARD_SQL = """
DROP TRIGGER IF EXISTS sr_auditlog_guard ON audit_auditlog;
DROP FUNCTION IF EXISTS sr_guard_auditlog();
"""


def add_trigger(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(FORWARD_SQL, params=None)  # raw SQL: no placeholder interpolation


def drop_trigger(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(BACKWARD_SQL, params=None)


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_alter_auditlog_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(redact_existing, migrations.RunPython.noop),
        migrations.RunPython(add_trigger, drop_trigger),
    ]
